-- 新增Restful数据源
INSERT INTO `dsc_type` ( `data_type`, `data_classify_id`, `weight`, `img_url`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `sorted`, `invisible`) VALUES ( 'Restful', 10, 3.0, 'Restful.png', 0, '2021-08-05 10:50:44', '2021-08-05 10:51:21', 0, 0, 900, 0);

-- 授权离线,实时
INSERT INTO `dsc_app_mapping` ( `app_type`, `data_type`, `data_version`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`) VALUES ( 1, 'Restful', '', 0, '2021-08-05 14:42:22', '2021-08-05 15:08:36', 0, 0);
INSERT INTO `dsc_app_mapping` ( `app_type`, `data_type`, `data_version`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`) VALUES ( 7, 'Restful', '', 0, '2021-08-05 14:42:22', '2021-08-05 15:08:36', 0, 0);

-- Restful表单
INSERT INTO `dsc_form_field` (`name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'portal', '协议:', 'Select', 1, 0, 'HTTP/HTTPS', '', NULL, 1, '', NULL, NULL, NULL, 0, '2021-08-05 11:07:27', '2021-08-05 11:07:27', 0, 0, 'Restful', '[{key:\'1\',value:\'HTTP/HTTPS\',label:\'HTTP/HTTPS\'}]');
INSERT INTO `dsc_form_field` (`name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'request-method', '请求方法:', 'Select', 1, 0, 'POST', '', NULL, 1, '', NULL, NULL, NULL, 0, '2021-08-05 11:07:27', '2021-06-29 19:00:52', 0, 0, 'Restful', '[{key:\'1\',value:\'POST\',label:\'POST\'},{key:\'2\',value:\'GET\',label:\'GET\'}]');
INSERT INTO `dsc_form_field` ( `name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ('url', 'URL:', 'Input', 1, 0, NULL, 'http(s)://xxxx', NULL, 1, '', NULL, NULL, NULL, 0, '2021-08-05 11:07:27', '2021-08-05 11:07:27', 0, 0, 'Restful', '');
INSERT INTO `dsc_form_field` ( `name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'header', 'Header 参数:', 'TextArea', 0, 0, NULL, NULL, NULL, 0, '', NULL, NULL, NULL, 0, '2021-08-05 11:07:27', '2021-08-05 11:07:27', 0, 0, 'Restful', '');