# NOTE: Generated By HttpRunner v3.1.4
# FROM: case_1.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCase1(HttpRunner):

    config = Config("UIC login case")

    teststeps = [
        Step(
            RunRequest("step 1")
            .post("/login")
            .with_params(
                **{
                    "username": "admin@dtstack.com",
                    "password": "hVd829YpNzkQ8rgITptkXuIIERE7EWAZFRVy/bY3IIKpTr5BjYgfukT6doRccd1jtgJbWX4xogEWSD3LrcMDC98wE4cgmXkGMTmmXg+8ZV15Zu9r8n8FBA1tVxyrzFbuEo5WPzaPMb4J5ygEdFbtwjTgqxgTRRs7nkasuztYqRQ=",
                    "verify_code": 0,
                }
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseCase1().test_start()
