CREATE TABLE `da_package_import` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0正常 1逻辑删除',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_user_id` int(11) NOT NULL COMMENT '创建的用户',
  `modify_user_id` int(11) NOT NULL COMMENT '修改的用户',
  `import_user_id` int(11) COMMENT '导入人',
  `state` int(1) COMMENT 'api包导入状态，6种',
  `package_name` varchar(255) NOT NULL COMMENT 'api包名称',
  `package_desc` varchar(255) NOT NULL COMMENT '描述',
  `md5_val` varchar(255) NOT NULL COMMENT 'md5值',
  `source_project` varchar(255) NOT NULL COMMENT '原项目名称',
  `source_tenant` varchar(255) NOT NULL COMMENT '原租户名称',
  `api_count` int(11) NOT NULL DEFAULT '0' COMMENT 'api总数量',
  `api_fail` int(11) NOT NULL DEFAULT '0' COMMENT 'API失败数量',
  `api_success` int(11) NOT NULL DEFAULT '0' COMMENT 'api成功数',
  `tenant_id` int(11) COMMENT 'id',
  `project_id` int(11) COMMENT 'id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT ='api包记录表';


CREATE TABLE `da_api_import` ( -- (修改,api导入表)
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
 -- `cat_id` int(11) COMMENT '类目ID',
 -- `tenant_id` int(11) NOT NULL COMMENT '租户ID',
 -- `data_src_id` int(11),
  `data_src_name` varchar(255),
  `api_cat_path` text,
  `package_id` int(11) NOT NULL COMMENT 'api包id',
  `import_state` int(11) DEFAULT '0' COMMENT '状态，成功or失败',
  `labels` text COMMENT 'api标签',
  `name` varchar(255),
  `table_name` varchar(255) DEFAULT '' COMMENT '目标表名',
  `req_limit` int(11) COMMENT '访问限制',
  `resp_limit` int(11),
  `api_type` varchar(45) DEFAULT '0' COMMENT 'api类型(0-默认,1-注册api)',
 -- `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态: 0:正常/1:禁用',
  `api_desc` text COMMENT '描述',
  `input_params` text ,
  `output_params` text ,
  `create_user_id` bigint(11) NOT NULL,
  `modify_user_id` bigint(11) NOT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `req_type` int(11) COMMENT '请求类型: 0:GET/1:POST',
  `api_path` varchar(255),
  `resp_page_size` int(11) COMMENT '分页大小',
  `param_cfg_type` int(11) DEFAULT '0' COMMENT '参数配置模式：0-向导模式，1-sql模式',
  `allow_paging` int(11) DEFAULT '0' COMMENT '是否分页：0-不分页，1-分页',
  `config_sql` text,
  `resp_json` text,
  `data_src_type` int(11) COMMENT '数据源类型',
  `original_host` varchar(255) DEFAULT NULL COMMENT '注册API的原始api host',
  `original_path` varchar(200) DEFAULT NULL COMMENT '注册api的原始api path',
  `original_method` varchar(255) DEFAULT NULL COMMENT '注册api原始请求方式。(枚举GET,POST,PUT)',
  `error_code_list_json` text COMMENT '注册api的错误码列表',
  `error_resp_json` text COMMENT '注册api的错误返回示例',
  `body_desc_json` varchar(1000) DEFAULT NULL COMMENT '注册api put、post请求body示例',
  `api_version_code` varchar(45) DEFAULT 'API_WITH_TOKEN',
  `wsdl_xml` text COMMENT 'wsdl xml 文件',
  `save_wsdl_xml` int(11) DEFAULT '0' COMMENT '是否存储 wsdl xml 标记， 0-不存储，1-存储',
  `protocol` varchar(20) DEFAULT NULL COMMENT '协议',
  `contain_header` int(11) DEFAULT '0' COMMENT '返回结果是否携带 header 中的输入参数， 0-不携带，1-携带',
  `contain_page` int(11) DEFAULT '0' COMMENT '返回结果是否携带 Page 分页信息， 0-不携带，1-携带',
  -- `project_id` int(11) DEFAULT NULL COMMENT '项目id',
  `query_time_out` int(11) COMMENT 'api查询超时时间',
 -- `test_status` int(11) NOT NULL DEFAULT '0' COMMENT 'da_api_test的api状态: 0:未提交/1:已提交',
 -- `is_secondary_release` int(11) DEFAULT '0' COMMENT '二次发布',
  `cn_name` varchar(255) DEFAULT NULL COMMENT 'api中文名称',
  `is_cache` tinyint(1) DEFAULT '0' COMMENT '是否缓存',
  `cache_expiry_period` int(11) DEFAULT NULL COMMENT '缓存失效周期，1-分，2-时，3-天，4-周，5-月',
  `cache_expiry_date_cron` varchar(255) DEFAULT NULL COMMENT '缓存失效时间的cron表达式',
  `is_ignore_syntax_check` tinyint(1) DEFAULT '0' COMMENT '是否忽略语法校验',
  `log` text COMMENT '操作日志',
  `api_id` int(11) COMMENT 'apiid',

  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

UPDATE da_role SET role_desc = 'API管理者，可进行API创建、发布、导入导出、管理、授权审批、用户管理，但不具备项目配置权限' WHERE role_value = 2