-- 新增Trino引擎支持
insert into dq_dict values (0, 1, 'Trino', 59, 'Trino', 'Trino', 13, now(), now(), 0);
-- dq_data_source_center兼容presto独立库设置
alter table dq_data_source_center add column `write_source_value` text  comment '独立库配置配置信息';
-- 新增Trino引擎函数模版
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (1, 59, 'select count(1)  as  val  from ${table} where 1=1 ${filter}', '');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (3, 59, 'select count(1) as val from ${table} where ${col} is null ${filter}', '${table} where ${col} is null ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (4, 59, 'select sum(case when ${col} is null then 1 else 0 end) * 1.00 / count(1) * 1.00 as val from ${table} where 1=1 ${filter}', '${table} where ${col} is null ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (5, 59, 'select sum(case when length(${col})=0 then 1 else 0 end) as val from ${table} where 1=1 ${filter}', '${table} where length(${col})=0 ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (6, 59, 'select sum(case when length(${col})=0 then 1 else 0 end) * 1.00 / count(1) * 1.00 as val from ${table} where 1=1 ${filter}', '${table} where length(${col})=0 ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (7, 59, 'select count(1) as val from (select count(${col}) from ${table} where 1=1 ${filter} group by ${col} having count(${col}) > 1) temp', '${table} t2 where exists (select  ${col} from ${table} t1 where 1=1 ${filter} ${unionFilter} group by ${col} having count(1) > 1)  ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (8, 59, 'select sum(case when count>1 then 1 else 0 end) * 1.00 / sum(count) * 1.00 as val from (select count(${col}) as count from ${table} where 1=1 ${filter} group by ${col}) temp', '${table} t2 where exists (select  ${col} from ${table} t1 where 1=1 ${filter} ${unionFilter} group by ${col} having count(1) > 1)  ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (9, 59, 'select count(1) as val from (select count(${col}) from ${table} where 1=1 ${filter} group by ${col} having count(${col}) = 1) temp', '${table} where ${col} in (select  ${col} from ${table} t1 where 1=1 ${filter} group by ${col} having count(${col}) > 1)  ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (10, 59, 'select sum(case when count=1 then 1 else 0 end) * 1.00 / sum(count) * 1.00 as val from (select count(${col}) as count from ${table} where 1=1 ${filter} group by ${col}) temp', '${table} where ${col} in (select  ${col} from ${table} t1 where 1=1 ${filter} group by ${col} having count(${col}) > 1)  ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (11, 59, 'select count(1) as val from  ${table} where  ${col} ${enum}  ${filter}', '${table} where ${col} ${enum} ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (12, 59, 'select approx_distinct(${col}) as val from ${table} where 1=1 ${filter}', '');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (13, 59, 'select sum(case when ${col} < 0 then 1 else 0 end) * 1.00 / count(1) * 1.00 as val from ${table} where 1=1 ${filter}', '${table} where ${col} < 0 ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (14, 59, 'select sum(case when ${col} = 0 then 1 else 0 end) * 1.00 / count(1) * 1.00 as val from ${table} where 1=1 ${filter}', '${table} where ${col} = 0 ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (15, 59, 'select sum(case when ${col} > 0 then 1 else 0 end) * 1.00 / count(1) * 1.00 as val from ${table} where 1=1 ${filter}', '${table} where ${col} > 0 ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (16, 59, 'SELECT max(length(${col})) as val from ${table} where 1=1 ${filter}', '${table} where length(${col})> ${expectation} ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (17, 59, 'SELECT min(length(${col})) as val from ${table} where 1=1 ${filter}', '${table} where length(${col})< ${expectation} ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (18, 59, 'select max(${col}) as val from ${table} where 1=1 ${filter}', '${table} where ${col}> ${expectation} ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (19, 59, 'select min(${col}) as val from ${table} where 1=1 ${filter}', '${table} where ${col}< ${expectation} ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (20, 59, 'select avg(${col}) as val from ${table} where 1=1 ${filter}', '');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (21, 59, 'select sum(${col}) as val from ${table} where 1=1 ${filter}', '');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (22, 59, 'SELECT count(1) AS val FROM ${table} WHERE regexp_like(${col},\'^[1-9][[:digit:]]{7}((0[[:digit:]])|(1[0-2]))(([0|1|2][[:digit:]])|3[0-1])[[:digit:]]{3}$|^[1-9][[:digit:]]{5}[1-9][[:digit:]]{3}((0[[:digit:]])|(1[0-2]))(([0|1|2][[:digit:]])|3[0-1])[[:digit:]]{3}([0-9]|X)$\') ${filter}', '${table} where NOT regexp_like (${col},\'^[1-9][[:digit:]]{7}((0[[:digit:]])|(1[0-2]))(([0|1|2][[:digit:]])|3[0-1])[[:digit:]]{3}$|^[1-9][[:digit:]]{5}[1-9][[:digit:]]{3}((0[[:digit:]])|(1[0-2]))(([0|1|2][[:digit:]])|3[0-1])[[:digit:]]{3}([0-9]|X)$\') ${filter}');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (23, 59, 'SELECT count(1) AS val FROM ${table} WHERE regexp_like(${col},\'^[1][35678][0-9]{9}$\') ${filter}', '${table} where ${filter} NOT regexp_like (${col},\'^[1][35678][0-9]{9}$\')');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (24, 59, 'SELECT count(1) AS val FROM ${table} WHERE regexp_like(${col},\'^[-[:alnum:]_]+@[-[:alnum:]_]+\\.[-[:alnum:]_]+$\')  ${filter}', '${table} where ${filter} NOT regexp_like (${col}, \'^[-[:alnum:]_]+@[-[:alnum:]_]+\\.[-[:alnum:]_]+$\')');
INSERT INTO `dq_function_template`(function_id, data_source_type, template, template_query) VALUES (25, 59, 'SELECT count(1) AS val FROM ${table} WHERE ${range}  ${filter}', '${table} where ${reverse_range} ${filter}');
